insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (1, 'Harry','Potter','James');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (2, 'Ronald','Weasley','Bilius');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (3, 'Hermione','Granger','Granger');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (4, 'Albus','Dumbledore','Percival Wulfric Brian');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (5, 'Lord ','Voldemort','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (6, 'Severus','Snape','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (7, 'Sirius','Black','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (8, 'Minerva','McGonagall','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (9, 'Ginny','Weasley','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (10, 'Neville','Longbottom','');
insert into CHARACTER (ID,FIRSTNAME,LASTNAME,MIDDLENAME) values (11, 'Bellatrix','Lestrange','');